name: HTML CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Verify HTML File Exists
      run: |
        echo "Checking HTML file..."
        ls
        if [ -f index.html ]; then
          echo "HTML file found successfully!"
        else
          echo "HTML file not found!"
          exit 1
        fi

    - name: Display Success Message
      run: echo "CI Pipeline Executed Successfully"
